LaptopWorldStore/Models/product.cs
namespace LaptopWorldStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("product")]
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            laptops = new HashSet<laptop>();
            rams = new HashSet<ram>();
            receiptbilldetails = new HashSet<receiptbilldetail>();
            sellbilldetails = new HashSet<sellbilldetail>();
            ssds = new HashSet<ssd>();
        }

        [Key]
        [StringLength(50)]
        [Display(Name = "Mã sản phẩm")]
        public string product_id { get; set; }

        [StringLength(50)]
        [Display(Name = "Mã loại")]
        public string category_id { get; set; }

        [StringLength(50)]
        [Display(Name = "Mã nhà cung cấp")]
        public string provider_id { get; set; }

        [Required]
        [StringLength(200)]
        [Display(Name = "Tên sản phẩm")]
        public string product_name { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Ảnh")]
        public string picture { get; set; }
        [Display(Name = "Giá bán")]
        public decimal price { get; set; }
        [Display(Name = "Số lượng")]
        public int quantity { get; set; }
        [Display(Name = "Miêu tả")]
        public string decription { get; set; }

        public bool flag { get; set; }

        public virtual category category { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<laptop> laptops { get; set; }

        public virtual provider provider { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ram> rams { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<receiptbilldetail> receiptbilldetails { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sellbilldetail> sellbilldetails { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ssd> ssds { get; set; }
    }
}

LaptopWorldStore/Areas/Admin/Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using LaptopWorldStore.Models;
using System.IO;

namespace LaptopWorldStore.Areas.Admin.Controllers
{
    public class productsController : Controller
    {
        private LaptopWorld db = new LaptopWorld();

        // GET: Admin/products
        public ActionResult Index(int page = 1)
        {
            var products = db.products.Include(p => p.category).Include(p => p.provider);
            return View(products.ToList().ToPagedList(page, 5));
        }

         [HttpGet]
        public ActionResult Index(string searchString, int page = 1)
        {
            var links = from l in db.products
                        select l;

            if (!String.IsNullOrEmpty(searchString))
            {
                links = links.Where(s => s.product_name.Contains(searchString));
            }

            return View(links.ToList().ToPagedList(page, 5));
        }
        // GET: Admin/products/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            ViewBag.laptop = db.laptops.FirstOrDefault(laptop => laptop.product_id == id);
            ViewBag.ram = db.rams.FirstOrDefault(ram => ram.product_id == id);
            ViewBag.ssd = db.ssds.FirstOrDefault(ssd => ssd.product_id == id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        public string Upload(HttpPostedFileBase picture, string link)
        {
            var filename = Path.GetFileName(picture.FileName);
            var url = "~/Content/images/product/" + link;
            var dicrectiontosave = Server.MapPath(Url.Content(url));
            var pathtosave = Path.Combine(dicrectiontosave, filename);
            picture.SaveAs(pathtosave);
            return link+filename;
        }
        public ActionResult Create()
        {
            ViewBag.category_id = new SelectList(db.categories, "category_id", "category_name", db.categories.First());
            ViewBag.provider_id = new SelectList(db.providers, "provider_id", "provider_name", db.providers.First());
            return View();
        }

        // POST: Admin/products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "product_id,category_id,provider_id,product_name,picture,price,quantity,decription,flag")] product product
                                     ,HttpPostedFileBase picture)
        {
            if(picture != null)
            {
                var filename = Path.GetFileName(product.category_id + "/" + picture.FileName);
                var dicrectiontosave = Server.MapPath(Url.Content("~/Content/images/product" ));
                var pathtosave = Path.Combine(dicrectiontosave,filename);
                picture.SaveAs(pathtosave);
                product.picture = filename;
            }
            
            if (ModelState.IsValid)
            {
                db.products.Add(product);            
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            ViewBag.category_id = new SelectList(db.categories, "category_id", "category_name", product.category_id.First());
            ViewBag.provider_id = new SelectList(db.providers, "provider_id", "provider_name", product.provider_id.First());
            return View(product);
        }

        // GET: Admin/products/Edit/5
        [HttpGet]
        public JsonResult GetAllProduct()
        {
            var list = db.products.Select(pd => new { pd.product_id, pd.product_name, pd.quantity, pd.price }).ToList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.category_id = new SelectList(db.categories, "category_id", "category_name", product.category_id);
            ViewBag.provider_id = new SelectList(db.providers, "provider_id", "provider_name", product.provider_id);
            return View(product);
        }

        // POST: Admin/products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "product_id,category_id,provider_id,product_name,picture,price,quantity,decription,flag")] product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.category_id = new SelectList(db.categories, "category_id", "category_name", product.category_id);
            ViewBag.provider_id = new SelectList(db.providers, "provider_id", "provider_name", product.provider_id);
            return View(product);
        }

      

        // POST: Admin/products/Delete/5
        [HttpPost]
        public string Delete(string id)
        {
            var product_in_bill = db.sellbilldetails.Where(dt => dt.product_id == id).FirstOrDefault();
            if(product_in_bill != null)
            {
                var pd = db.products.Find(id);
                pd.flag = false;
                db.SaveChanges();
                return "hideproduct";
            }
            product product = db.products.Find(id);
             db.laptops.RemoveRange(db.laptops.Where(lt => lt.product_id == product.product_id));
            db.rams.RemoveRange(db.rams.Where(lt => lt.product_id == product.product_id));
            db.ssds.RemoveRange(db.ssds.Where(lt => lt.product_id == product.product_id));
            db.products.Remove(product);
            db.SaveChanges();
            return "deletesuccessful";
        }
        public ActionResult Signout()
        {
            Session.Clear();
            return RedirectToAction("Index", "home", new { area = "" });
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LaptopWorldStore/Controllers/productsController.cs
using LaptopWorldStore.Models;
using Newtonsoft.Json;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace LaptopWorldStore.Controllers
{
    public class productsController : Controller
    {
        private LaptopWorld db = new LaptopWorld();

        // GET: products
        public ActionResult Index()
        {
            var products = db.products.Include(p => p.category);
            return View(products.ToList());
        }

        // GET: products/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        
        public JsonResult GetProduct()
        {
            var products = db.products.Select(pd => new { pd.product_id, pd.product_name}).ToList();
            return Json(products, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Laptoppage()
        {
            var products = db.products.Include(p => p.category).Where(p => p.category_id == "laptop"); ;
            return View(products.ToList());
        }

        public ActionResult Ssdpage()
        {
            var products = db.products.Include(p => p.category).Where(p => p.category_id == "ssd"); ;
            return View(products.ToList());
        }
    }
}

LaptopWorldStore/Areas/Admin/Views/products/Create.cshtml
@model LaptopWorldStore.Models.product

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h4 class="page-title">Sản phẩm</h4>


<div class="form-create">
    @using (Html.BeginForm("Create", "products", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.product_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category_id", null,  new { @class = "form-control", @onclick = "Log(this.value)" })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.provider_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("provider_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.provider_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.product_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="picture" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.decription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.decription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.decription, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.flag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.flag)
                    @Html.ValidationMessageFor(model => model.flag, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
    }


</div>
<script>
    function Log(val){
        console.log(val);
    }
</script>

LaptopWorldStore/Areas/Admin/Views/products/Index.cshtml
@model IPagedList<LaptopWorldStore.Models.product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

}
@using PagedList;
@using PagedList.Mvc;

<h4 class="page-title">Sản phẩm</h4>

<div class="main-content" ng-controller="adminproduct">
    <div class="function-place">
        <select ng-model="product.category_id">
            <option value="laptop">Laptop</option>
            <option value="ssd">ssd</option>
            <option value="ram">ram</option>
        </select>
        <a ng-click="RedicrecToCreatePage()" class="btn fas fa-plus">Thêm mới</a>
    </div>
    <div class="table-function-place">
        @using (Html.BeginForm("Index", "products", FormMethod.Get))
        {

            @Html.TextBox("SearchString") <input class="btn search-btn" type="submit" value="Tìm kiếm" />

        }
    </div>
    <table id="dynamic-table" class="table table-hover table-striped">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.First().category.category_name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().provider.provider_name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().product_name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().picture)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().quantity)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.First().flag)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.category.category_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.provider.provider_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.product_name)
                    </td>
                    <td class="col-lg-2">
                        <img src="@Url.Content("~/Content/images/product/" + item.picture)" />
                    </td>
                    <td>
                        @string.Format("{0:#,###,000}", item.price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.quantity)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.flag)
                    </td>
                    <td>
                        @Html.ActionLink(" ", "Edit", item.category_id + "s", new { id = item.product_id }, new { @Class = "text-primary far fa-edit table-button" })
                        @Html.ActionLink(" ", "Details",item.category_id+"s", new { id = item.product_id }, new { @Class = "gray fas fa-info-circle table-button" })
                        <a class="text-danger far fa-trash-alt table-button" ng-click="DeleteProduct('@item.product_id')"></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @Html.PagedListPager(Model, page => Url.Action("Index", "products", new { page, searchString = Request.QueryString["searchString"] }),
                                                                                   new PagedListRenderOptions
                                                                                        {
                                                                                      ContainerDivClasses = new string[] { "page-item" }
                                                                                   })
</div>
<script src="~/Content/js/admin-product.js"></script>