LaptopWorldStore/Models/customer.cs
namespace LaptopWorldStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("customer")]
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            sellbills = new HashSet<sellbill>();
        }
        [Key]
        [Display(Name = "Mã nhân viên")]
        public Guid customer_id { get; set; }

        [StringLength(15)]
        [Display(Name = "Số điện thoại")]
        public string phonenumber { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Tên nhân viên")]
        public string customer_name { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Địa chỉ")]
        public string address { get; set; }

        public bool flag { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sellbill> sellbills { get; set; }
    }
}

LaptopWorldStore/Areas/Admin/Controllers/customersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using LaptopWorldStore.Models;

namespace LaptopWorldStore.Areas.Admin.Controllers
{
    public class customersController : Controller
    {
        private LaptopWorld db = new LaptopWorld();

        // GET: Admin/customers
        public ActionResult Index(int page = 1)
        {
            return View(db.customers.ToList().ToPagedList(page, 10));
        }

         [HttpGet]
        public ActionResult Index(string searchString, int page = 1)
        {
            var links = from l in db.customers
                        select l;

            if (!String.IsNullOrEmpty(searchString))
            {
                links = links.Where(s => s.customer_name.Contains(searchString));
            }

            return View(links.ToList().ToPagedList(page, 10));
        }
        // GET: Admin/customers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Admin/customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "phonenumber,customer_name,address,flag")] customer customer)
        {
            if (ModelState.IsValid)
            {
                customer.customer_id = Guid.NewGuid();
                db.customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Admin/customers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Admin/customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "phonenumber,customer_name,address,flag")] customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Admin/customers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Admin/customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            customer customer = db.customers.Find(id);
            db.customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LaptopWorldStore/Areas/Admin/Views/customers/Create.cshtml
@model LaptopWorldStore.Models.customer

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h4 class="page-title">Khách hàng</h4>


<div class="form-create">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.phonenumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.phonenumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.phonenumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.customer_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.customer_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.customer_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.flag, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.flag)
                        @Html.ValidationMessageFor(model => model.flag, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    }


</div>

LaptopWorldStore/Areas/Admin/Views/customers/Delete.cshtml
@model LaptopWorldStore.Models.customer

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h4 class="page-title">Khách hàng</h4>


<div class="form-delete">
    <h3>Bạn có chắc chắn xóa?</h3>
    <div>

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.customer_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.customer_name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.address)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.address)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.flag)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.flag)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Xóa" class="btn btn-danger" />
                @Html.ActionLink("Quay lại", "Index", "", new { @class = "btn btn-default" })
            </div>
        }
    </div>
</div>

LaptopWorldStore/Areas/Admin/Views/customers/Details.cshtml
@model LaptopWorldStore.Models.customer

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h4 class="page-title">Khách hàng</h4>


<div class="form-edit">
    <div>

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.customer_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.customer_name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.address)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.address)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.flag)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.flag)
            </dd>

        </dl>
    </div>
    <p style="margin-left: 3rem">
        @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.phonenumber }, new { @class = "btn btn-primary" })
        @Html.ActionLink("Quay lại", "Index", "", new { @class = "btn btn-default" })
    </p>
</div>

LaptopWorldStore/Areas/Admin/Views/customers/Edit.cshtml
@model LaptopWorldStore.Models.customer

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h4 class="page-title">Khách hàng</h4>


<div class="form-edit">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.phonenumber)

            <div class="form-group">
                @Html.LabelFor(model => model.customer_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.customer_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.customer_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.flag, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.flag)
                        @Html.ValidationMessageFor(model => model.flag, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-primary" />
                    @Html.ActionLink("Quay lại", "Index", "", new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    }

</div>

LaptopWorldStore/Areas/Admin/Views/customers/Index.cshtml
@model IPagedList<LaptopWorldStore.Models.customer>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@using PagedList;
@using PagedList.Mvc;

<h4 class="page-title">Khách hàng</h4>

<div class="main-content">
    <div class="function-place">
            @Html.ActionLink(" Thêm mới", "Create", new { }, new { @class = "btn fas fa-plus" })
    </div>
    <div class="table-function-place">
            @using (Html.BeginForm("Index", "customers", FormMethod.Get))
            {

                @Html.TextBox("SearchString") <input class="btn search-btn" type="submit" value="Tìm kiếm" />

            }
    </div>
    <table id="dynamic-table" class="table table-hover table-striped">
        <thead class="thead-dark">
                <tr>
                                                        <th>
                        @Html.DisplayNameFor(model => model.First().customer_name)
                    </th>
                                            <th>
                        @Html.DisplayNameFor(model => model.First().address)
                    </th>
                                            <th>
                        @Html.DisplayNameFor(model => model.First().flag)
                    </th>
                                <th></th>
                </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                                        <td>
                    @Html.DisplayFor(modelItem => item.customer_name)
                </td>
                                <td>
                    @Html.DisplayFor(modelItem => item.address)
                </td>
                                <td>
                    @Html.DisplayFor(modelItem => item.flag)
                </td>
                        <td>
                    @Html.ActionLink(" ", "Edit", new { id=item.phonenumber } , new { @Class = "text-primary far fa-edit table-button" }) 
                    @Html.ActionLink(" ", "Details", new { id=item.phonenumber } , new { @Class = "gray fas fa-info-circle table-button" }) 
                    @Html.ActionLink(" ", "Delete", new { id=item.phonenumber }, new { @Class = "text-danger far fa-trash-alt table-button" })
                </td>
                    </tr>
        }
    </tbody>
    </table>
    @Html.PagedListPager(Model, page => Url.Action("Index", "customers", new { page, searchString = Request.QueryString["searchString"] }),
                                                                                   new PagedListRenderOptions
                                                                                        {
                                                                                      ContainerDivClasses = new string[] { "page-item" }
                                                                                   })
</div>    