LaptopWorldStore/Models/account.cs
namespace LaptopWorldStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("account")]
    public partial class account
    {
        [StringLength(50)]
        [Display(Name =" Mã nhân viên")]
        public string employee_id { get; set; }

        [Key]
        [StringLength(100)]
        [Display(Name = "Tài Khoản")]
        public string username { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Mật khẩu")]
        public string password { get; set; }

        public virtual employee employee { get; set; }
    }
}

LaptopWorldStore/Controllers/accountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using LaptopWorldStore.Models;

namespace LaptopWorldStore.Controllers
{
    public class accountsController : Controller
    {
        private LaptopWorld db = new LaptopWorld();

        // GET: accounts
        public ActionResult Index()
        {
            var accounts = db.accounts.Include(a => a.employee);
            return View();
        }

         [HttpGet]
        public ActionResult Index(string username, string password)
        {
            
            if (username != null)
            {
                if (Check(username, password) == "success")
                {
                    ViewBag.Fail = "";
                    Session["Username"] = username;
                    return RedirectToAction("Index", "products", new { area = "Admin" });
                }
                else
                {
                    ModelState.AddModelError("FailSignin", "Sai tài khoản hoặc mật khẩu");
                }
            }
         

            return View();
        }
       public string Check(string username, string password)
        {
            account acc = new account();
          
             acc = db.accounts.Where(a => a.username.Equals(username) && a.password.Equals(password)).FirstOrDefault();
            if(acc != null)
            {
                return "success";
            }
            else
            {
                return "fail";
            }
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LaptopWorldStore/Views/accounts/Index.cshtml
@model LaptopWorldStore.Models.account

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="main col-4 marginauto ">


   
        @using (Html.BeginForm("Index", "accounts", FormMethod.Get, new {@Class = "marginauto singin-form col-lg-12" }))
        {
            <div class=" col-11 marginauto">
                <label>Tài khoản:</label>
                @Html.TextBoxFor(m => m.username, "", new { @class = "col-12", @placeholder = "First Name" })
                @Html.ValidationMessageFor(m => m.username, "", new { @class = "badge badge-danger" })
            </div>

            <div class="col-11 marginauto">
                <label>Mật khẩu:</label>
                @Html.PasswordFor(m => m.password, new { @class = " col-12", @placeholder = "First Name" })
                @Html.ValidationMessageFor(m => m.password, "", new { @class = "badge badge-danger" })
            </div>
            <p class="col-11 marginauto">
                @Html.ValidationMessage("FailSignin", new {@class= "text-danger" })
            </p>
            <div class="col-11 marginauto">
                <input class="btn btn-danger col-12" type="submit" id="submit" value="Đăng nhập" />
            </div>
           

        }
  



</div>
<link href="~/Content/css/signin.css" rel="stylesheet" />

   